### PR TITLE
Option to add custom background color

### PR DESCRIPTION
**Pull request by BijanRegmi**
#17

### CODE REVIEW

**Comment by datguysheepy** [comment]
Wow, I wasn't expecting anyone to touch this old project of mine :smile: (there are still `vars` everywhere)

As all the icons in this project are from [here](https://heroicons.com/) I would prefer to have that "edit" svg copied from there as well (just copy and paste the svg code in the correct place and add className - have a look at this  #21  PR if needed).
I'm not really big fan of using prompt and I would prefer using custom modal (just like for creating group/bookmark) but I think it's too much for this functionality so I would leave it like it is.

**Comment by BijanRegmi** [comment]
Okay, b3a8922 addresses these concerns. I've reused the create group modal while setting the bg value. And the svg image has also been updated.

**Comment by datguysheepy** [comment]
Looks good now, thanks. For now I'll accept this PR but I'll not merge it yet

**Comment by datguysheepy** [comment]
As a complete extension redesign is done I will close PR completely as is not needed anymore, but thanks for the help :smile: 
Have a look at the redesigned version and maybe you will find something that you could improve, and this time it will be merged :stuck_out_tongue:

**Pull request closed without merging**
